apiVersion: v1
kind: Secret
metadata:
  name: controller-manager-gh-credentials
  namespace: arc-systems
  labels:
    app.kubernetes.io/name: gha-runner-scale-set-controller
    app.kubernetes.io/managed-by: clusterbox
type: Opaque
stringData:
  github_token: "${GH_PAT_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager-gh-credentials
  namespace: arc-runners
  labels:
    app.kubernetes.io/name: gha-runner-scale-set-controller
    app.kubernetes.io/managed-by: clusterbox
type: Opaque
stringData:
  github_token: "${GH_PAT_TOKEN}"
