apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse-operator
  labels:
    app.kubernetes.io/managed-by: clusterbox
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/managed-by: clusterbox
