apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-telemetry-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/managed-by: clusterbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
